version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: icebank-postgres
    environment:
      POSTGRES_DB: icebank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: icebank-app
    depends_on:
      - postgres
    ports:
      - "8082:8082"
    env_file:
      - .env

volumes:
  postgres_data: